### ISSUE TITLE
Players can see each other's maps

### ISSUE THREAD

**Issue by MaXFeeD** [MemoriesOfTime/Nukkit-MOT#102]
# ❇ Future Request | 特性请求

## 📝 Detailed Description | 详细说明

If you throw map you created to another player, it will be empty for everyone except you.

## 📸 Screenshots / Video | 截图或视频

![Screenshot_20231122-235432](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/46795182/5c4148b4-2dd5-483e-b646-a4800ca1184d)
![Screenshot_20231123-000106](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/46795182/6dfcb7ff-1d32-4152-b429-25c5b44c038c)

**Comment by glorydark** [comment]
Definitely quite weird. In others' hand, the map vanishes. Plz wait for the fix soon.
