### ISSUE TITLE
The bug with logging into the account of a player who is currently online.

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#124]
🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
When a player is online and another player logs into the account of the player who is online, the player who is online gets disconnected from the server, and the player who is connecting logs into their account.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

**Comment by m3fri** [comment]
The bug involves logging into the account of a player who is currently online. For example, player Steve is playing on the server, and another player logs in with the exact same username. This action kicks out player Steve and allows the other player to access the account.

**Comment by lt-name** [comment]
enable xbox

**Comment by m3fri** [comment]
> enable xbox

no, fix this, I don’t have an xbox on my server, it’s a pain in the ass to make an xbox for players from Russia. This is statistics.

**Comment by BlusteryS** [comment]
> no, fix this, I don’t have an xbox on my server, it’s a pain in the ass to make an xbox for players from Russia. This is statistics.

Almost all servers have already switched to xbox.
Sometimes the game can crash, it helps to quickly rejoin and not wait for the automatic kick

**Comment by lt-name** [comment]
Turning off xbox login will cause the core to be unable to determine who is the real player, so kicking one out is a normal operation
If you have special needs you can write a plugin to check
