### ISSUE TITLE
玩家蹲下时进行传送会出现无法移动和视角

### ISSUE THREAD

**Issue by Nissining** [MemoriesOfTime/Nukkit-MOT#127]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述
玩家蹲下时进行传送会出现无法移动和视角

## 🔍 Steps to Reproduce | 复现方法
初步判断是玩家蹲下时进行传送会出现无法移动和视角

## 📸 Screenshots / Video | 截图或视频

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/3067ac06-5ec7-453f-bc1c-589496696623

![img_v3_025u_be8dcb63-f4e2-46d0-84ae-16cd8ff08eag](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/e6dd6f4e-4722-4d41-9973-d2c5dd6c42f7)

## 💻 OS and versions | 操作系统和核心版本
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/ff577eef-33b1-4dbf-93fb-c52a17cc2a13)

**Comment by lt-name** [comment]
在 https://github.com/MemoriesOfTime/Nukkit-MOT/commit/ed30182df40e2e8b6bfebc6ac060cd03628a661d 中修复，请更新到最新版本测试
