### ISSUE TITLE
teleports down when entering the server

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#128]
🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
When you join the server, it teleports you under the ground by 1-2 blocks, and then throws you up by 1-2 blocks (sometimes everything is normal). Tested on hosting, possibly due to ping issues. I don't have any plugins installed.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/142756404/0efdab85-ac80-4f19-9646-9c80145712be

**Comment by lt-name** [comment]
Fixed in https://github.com/MemoriesOfTime/Nukkit-MOT/commit/3dcbd5aa9e0bd3874ff9c75a3a0152a1be956989
