### ISSUE TITLE
When trying to fetch an offline player, I get null. My player-data is disabled.

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#131]
🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
When trying to fetch an offline player, I get null. My player-data is disabled.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

**Comment by lt-name** [comment]
Xbox online and offline players uuid are different
