### ISSUE TITLE
两个小bug,望修复

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/Nukkit-MOT#174]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

1.空指针报错,见日志
2.addParticle的粒子对应不上了,例如:生成LavaDripParticle会变成WaterDripParticle

## 💻 OS and versions | 操作系统和核心版本

Build: master/efee895
客户端版本1.20.60
..

## 📝 Logs | 日志

![QQ图片20240211185044](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/21009992/caf7ace0-3481-4b04-a3e4-684c4b94a8bd)

****

**Comment by lt-name** [comment]
粒子问题已修复

**Comment by lt-name** [comment]
blocksAround空指针通常为异步操作实体导致，已改为忽略报错
请更新到最新版测试
