### ISSUE TITLE
使用定位地图创建地图，地图会变成普通地图

### ISSUE THREAD

**Issue by smallcat9669** [MemoriesOfTime/Nukkit-MOT#187]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

如标题，当使用定位地图创建地图的时候，地图会被重置为普通地图.

## 💻 OS and versions | 操作系统和核心版本
核心使用的版本是: 955ed1ef3adbaea9e4b0de80b4f5944226e9e01d/955ed1e | https://github.com/MemoriesOfTime/Nukkit-MOT/actions/runs/7910424345
客户端版本: 1.20.12

## 📸 Screenshots / Video | 截图或视频
https://github.com/MemoriesOfTime/Nukkit-MOT/assets/114364961/12075c70-ffcc-4438-8f4d-43a2b0c0f458

**Comment by lt-name** [comment]
定位地图功能尚未实现
