### ISSUE TITLE
诡异菌根与绯红菌根不会自动掉落

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#19]
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/2b48254f-c313-4ae8-a09b-ad0492fee048)
如图，当诡异菌根下方的方块被破坏后，诡异菌根不会更新状态

**Comment by lt-name** [comment]
已修复，请更新到最新版测试
