### ISSUE TITLE
自定义工具难以破坏如带釉陶瓦,管珊瑚块等新版方块

### ISSUE THREAD

**Issue by Antique233** [MemoriesOfTime/Nukkit-MOT#191]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

自定义工具难以破坏如带釉陶瓦,管珊瑚块等新版方块

注册物品代码如下
```
    public static class customitem extends CustomToolBase {
        private static String sid = "item514";
        public static String name = sid;
        public customitem() {
            super(sid,name);
        }

        @Override
        public int getTier() {
            return TIER_DIAMOND;
        }
        @Override
        public int getToolSpeed() {
            return 12;
        }

        @Override
        public boolean isPickaxe() {
            return true;
        }
    }
```

## 📸 Screenshots / Video | 截图或视频

第一个用的是自定义镐子,可以正常破坏石头,但是难以破坏带釉陶瓦,管珊瑚块
第二个是钻石镐,可以正常破坏所有三种方块

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/21009992/64dc9875-1339-4d91-9fbe-93584808855a

## 💻 OS and versions | 操作系统和核心版本

Build: master/d84c74a

**Comment by lt-name** [comment]
可能是自定义物品的可挖掘方块列表不全
最近在忙其他事，得晚几天再修
