### ISSUE TITLE
1.12 multiversion crash

### ISSUE THREAD

**Issue by JoggingSplash** [MemoriesOfTime/Nukkit-MOT#199]
# 🐞 Bug Feedback | BUG反馈

## 🔍 Steps to Reproduce | 复现方法

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## 💻 OS and versions | 操作系统和核心版本

* Version: ✍
* Java: OracleJDK/GraalVM/AdoptOpenJDK 
* Java version: 17 
* Game version: Android/iOS/Win10/Xbox/PS4/Switch 

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by lt-name** [comment]
Temporarily fixed
