### ISSUE TITLE
重构数据包架构导致npc dialog无法响应

### ISSUE THREAD

**Issue by Mcayear** [MemoriesOfTime/Nukkit-MOT#205]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

在此 https://github.com/MemoriesOfTime/Nukkit-MOT/commit/a7043fd73ec8daf5bcc135ca856a3800be5f12e2 提交之后的 nukkit-mot 使用rsnpc的dialog点击按钮不再正常工作。

也无法关闭。

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/48203962/ebfb091b-4854-41da-bc21-19cca92143db

控制台没有更多log信息。

**Comment by lt-name** [comment]
更新到最新构建测试

**Comment by glorydark** [comment]
Solved
