### ISSUE TITLE
leveldb无法加载告示牌内容

### ISSUE THREAD

**Issue by jlhsr** [MemoriesOfTime/Nukkit-MOT#206]
# 🐞 
使用一张带有木牌内容的1.20.10存档放入mot进行加载  》 木牌为空
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/f5a01cce-bcae-48e4-ae94-4c507fd31cb7)
》
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/d66c92c2-de43-419f-b37d-c75a4ba65ec8)

**Comment by lt-name** [comment]
已修复
