### ISSUE TITLE
[隐患]leveldb地图无法保存/读取gamerules

### ISSUE THREAD

**Issue by jlhsr** [MemoriesOfTime/Nukkit-MOT#207]
复现步骤
进入一张ldb地图》》设置gamerule》》重启服务器》》未被保存
<img width="1280" alt="dea7d595df22454eaaba88be590c2bd2" src="https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/07be0e19-3965-4d5c-9472-94ff5c8657f4">

**Comment by lt-name** [comment]
已修复
