### ISSUE TITLE
leveldb地图与FuturePlots生成器之间的兼容

### ISSUE THREAD

**Issue by jlhsr** [MemoriesOfTime/Nukkit-MOT#228]
<img width="1280" alt="eeea84c93c6d4b121ca098862b327ff9" src="https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/264cdd0f-8223-4042-830c-db6f55f9781f">
leveldb的图就无法使用FuturePlots的生成器
测试插件版本FuturePlots-3.3.4-SNAPSHOT
地址https://github.com/tim03we/FuturePlots/releases

**Comment by KoshakMineDEV** [comment]
Plugin is archived and support of it is not guranteed.
