### ISSUE TITLE
Inventory security issue

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/Nukkit-MOT#23]
With the help of various cheats (CheatEngine, gophertunnel, etc), players can give themselves any items, even with their own nbt tags, through the anvil, enchantment and some other inventories.

This can become a serious threat to the server, because players can get any items, use their nbt and other item parameters.
This can be fixed by doing server side checks.

## Examples
https://youtu.be/5rX8m-YcmVU
https://youtu.be/PxWoFHwElIg

**Comment by lt-name** [comment]
Please update to the latest version and test.

**Comment by BlusteryS** [comment]
The check should be somewhere deeper, in canExecute() `outputItem.getId()` still equals `inputItem.getId()`

This is my golang code that fakes an item:
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/52814854/0eee215f-cfda-4d8e-b01a-a6b8deadb9e2)

**Comment by lt-name** [comment]
It's not convenient to discuss here.
Please refer to Discord for further information.

**Comment by lt-name** [comment]
I added another check that, Please update to the latest version to test

**Comment by BlusteryS** [comment]
Fixed
