### ISSUE TITLE
异常增大的leveldb地图体积

### ISSUE THREAD

**Issue by jlhsr** [MemoriesOfTime/Nukkit-MOT#236]
leveldb地图会随着服务器运行时长逐渐增加 
即使生成的实体已经.setCanBeSavedWithChunk(false)
<img width="241" alt="78c2b307df9fa7eb0adaf46d24c35359" src="https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/ee852dfb-9509-4a73-9252-53fd375c50b3">
如何复现？？
导入一张leveldb格式的地图
玩家进入地图后 stop关服 如此循环操作
您会发现 该地图区块文件数目逐渐增加   即使玩家没有跑图 且除了进入地图没有其他操作
<img width="894" alt="fad44cb40c972c8fbedfb43404c4c593" src="https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/40b771d1-141e-45fb-b7eb-c097b73eb0e6">
<img width="894" alt="07d8006e746e3c1586c939bf983b22e9" src="https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22098995/9eabafc9-40f7-43b5-b208-fcc63e77e268">

**Comment by Mcayear** [comment]
在 server.properties 文件将 use-native-leveldb 改为 on
