### ISSUE TITLE
有些方塊登入時，它顯示試圖載入，求解

### ISSUE THREAD

**Issue by MrBandi** [MemoriesOfTime/Nukkit-MOT#252]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

我把單人世界的地圖移動到Server上後，登入進去一堆方塊顯示?
終端那邊跳出一堆警告，我想要了解，有甚麼方式可以解決?

## 🔍 Steps to Reproduce | 复现方法

希望可以修復這個問題

## 📸 Screenshots / Video | 截图或视频
* 這個是單人世界的樣子，它是拋光安山岩
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/66209699/1e0ff319-e068-4f72-8a52-b5d0b8377fed)

* 這個是Server進去後的樣子
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/66209699/a22e0a96-138e-4036-a37f-adf5a95eeef5)

* 這個是Server終端的樣子
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/66209699/c98e7550-1f7a-42b4-955d-1c5721ce9ed5)

## 💻 OS and versions | 操作系统和核心版本

* Version: 1.20.80
* Java: OracleJDK
* Java version: 21
* Game version: Win10

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by lt-name** [comment]
Many blocks after 1.16 are not supported
We will gradually add these blocks, but it will take time

**Comment by Mcayear** [comment]
### 中文：
对于 Nukkit-MOT 已支持但没有显示的方块，使用 https://chunker.app 转换地图为 **基岩 1.20.10** 版本的地图即可。

Nukkit-MOT 未支持的方块仍然会保持 `info_update` 方块。

### English:
For blocks that are supported by Nukkit-MOT but are not displayed, use https://chunker.app to convert the map to the **Bedrock 1.20.10** version of the map.

Blocks not supported by Nukkit-MOT will still stay the `info_update` block

**Comment by MrBandi** [comment]
歐窺歐虧~感謝
