### ISSUE TITLE
Trident "with loyalty enchantment" is not at all loyal

### ISSUE THREAD

**Issue by XieLongOwner** [MemoriesOfTime/Nukkit-MOT#256]
# 🐞 Bug Feedback

**Comment by XieLongOwner** [comment]
Loyalty "disloyalty" Can't return to the player
Channeling ′s Lightning can attack the trident. make the trident disappear

**Comment by CoolMagic233** [comment]
> Loyalty "disloyalty" Can't return to the player Channeling ′s Lightning can attack the trident. make the trident disappear

How lightning attacks the trident?
