### ISSUE TITLE
Bug drop buttons

### ISSUE THREAD

**Issue by StefanFox-Dev** [MemoriesOfTime/Nukkit-MOT#261]
# 🐞 Bug Feedback | BUG反馈

## 🔍 Steps to Reproduce | 复现方法

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## 📸 Screenshots / Video | 截图或视频

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/59245729/885fe1e1-ce78-44db-aaf7-7d2c42486168

## 💻 OS and versions | 操作系统和核心版本

* Version: 1.20.80
* Java: OracleJDK 
* Java version: 21 
* Game version: Android/iOS/Win10/Xbox/PS4/Switch 

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by glorydark** [comment]
lt-name told me that buttons are only registered, but the block states of all buttons are not checked and supplemented.

**Comment by glorydark** [comment]
I will tell Name about this.
