### ISSUE TITLE
Memory leak when using LevelDB

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/Nukkit-MOT#272]
# 🐞 Bug Feedback

## 📝 Bug Description
When using LevelDB (no matter native or default), a large memory leak occurs. Objects appear that java cannot remove. In 5 minutes of flying around the world, about 1200 MB accumulated (not counting the 800 MB that is required for the start and login of the player).

When using anvil, even when loading chunks for 10-15 minutes, memory usage remains at ~ 800 MB (sometimes even less, it does not increase).

When using custom generators, values ​​can exceed 3 GB in a few minutes

I profiled the process through YourKit, but didn't find anything. 800 MB - not reachable to GC.

## 📸 Screenshots / Video
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/52814854/b2f31738-e08a-4423-8be7-125b8559e7d0)
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/52814854/441be5c7-76c3-4301-8ae1-804b2bc37ed6)

## 💻 OS and versions
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/52814854/c42392ea-1469-4826-a5a6-248d0fe121d6)

* Version: 1.20.80
* Java: OracleJDK, GraalVM
* Java version: 22

**Comment by BlusteryS** [comment]
When using Parallel GC does not catch Out Of Memory, but memory still grows to the maximum.

I think the problem is in the library providing the leveldb implementation, but Java profilers can't find the reason.

**Comment by KoshakMineDEV** [comment]
Looks like fixed after #340
