### ISSUE TITLE
Water doesn't render properly in Minecraft Education PRE-1.9

### ISSUE THREAD

**Issue by OptiJuegos** [MemoriesOfTime/Nukkit-MOT#278]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

When playing with an education cracked version of the game (older than 1.12.0), the water texture doesn't appear 
I tried on android with the OpenGL render and it worked perfectly

On original BDS it also works fine

## 🔍 Steps to Reproduce | 复现方法

Play the game in an older version than 1.12.0

## 📸 Screenshots / Video | 截图或视频

Education Cracked 1.7-1.9 
https://github.com/MemoriesOfTime/Nukkit-MOT/assets/94207445/998a6e6e-acb6-4820-a4c4-1edca295d860
Android 1.9
![9b7302a8-28c9-415b-96c7-a8637618fbde](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/94207445/4adb2fc5-84c3-4d12-a81a-b4c940afe87d)
UWP Win10 1.8
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/94207445/355db436-ea16-49f2-a751-6506f3c73f55)

## 💻 OS and versions | 操作系统和核心版本

* Version: MOT 1.20.80 & PetteriM1 1.20.10
* Java: OracleJDK Libreica
* Java version: 17 & 21
* Game version: 1.9, 1.7, 1.12 Education Cracked | 1.9 Android | 1.8 & 1.9 UWP Win10

## 💡 Possible Solution | 

I tested copying hlsl shaders to education and it didn't worked, also water textures and materials and original assets

**Comment by OptiJuegos** [comment]
Same issue happends in 1.7

**Comment by BlusteryS** [comment]
Have you tried this on the original version of the game?

**Comment by OptiJuegos** [comment]
Yep, it works in the original version of the game

**Comment by explorer3039** [comment]
maybe it's a runtime block state bug

**Comment by lt-name** [comment]
The core is not currently compatible with the educational version, please use the official version
