### ISSUE TITLE
Bug | 告示牌呈现内容错误

### ISSUE THREAD

**Issue by FTS427** [MemoriesOfTime/Nukkit-MOT#285]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

如题， Nukkit-MOT 存在着告示牌呈现内容错误，表现为告示牌内容在输入时从最底端开始输入而非如原版 BDS 从告示牌中央开始提示输入，并且在换行后上一行不会被提升

## 🔍 Steps to Reproduce | 复现方法

1. 进入一个 Nukkit-MOT 服务器
2. 通过一些手段获得一个告示牌
3. 置于地上，会发现提示输入的光标从告示牌最底端中间开始提示玩家输入，随意输入一些较长的内容
4. See unexpected behavior 😕 ✍

## ✅ Expected Behavior | 预期行为

如原本 BDS 一样从告示牌中央提示玩家输入，换行或文本较长自动换行时将上面的内容的高度提升

## 📸 Screenshots / Video | 截图或视频

![Screenshot_2024-06-27-15-12-49-486.jpeg](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/122330825/6581d447-569c-4b91-83bc-8d6e440b6424)

## 💻 OS and versions | 操作系统和核心版本

* Version: master/eec7fc9 
* Java: OpenJDK 64-bit Server VM Azul Systems
* Java version: 17.0.11+9 LTS
* Game version: 1.21.0
* Gaming platform: Android

## 💡 Possible Solution | 可能的解决方案

Idk

## 📝 Logs | 日志

此 bug 出现时控制台无输出，无需日志文件

**Comment by Mcayear** [comment]
可以使用输入法 _**删除键**_ 去掉多余的换行符。

**Comment by FTS427** [comment]
是的，可以这样，但是我认为让告示牌在初始时让光标移到第一次会好些，避免出现像我这样的小白来问
