### ISSUE TITLE
Snappy Crashes

### ISSUE THREAD

**Issue by BlusteryS** [MemoriesOfTime/Nukkit-MOT#295]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述
Many players are crashing when trying to join the server. This is because Snappy is enabled.

If you turn off snappy, the login occurs normally.

OS: Windows, Android, etc
Server OS: Windows, Linux, etc
Java: 21, 17, ...

**Comment by lt-name** [comment]
Changed to off by default
