### ISSUE TITLE
书架bug

### ISSUE THREAD

**Issue by explorer3039** [MemoriesOfTime/Nukkit-MOT#301]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

mot的书架从创造模式物品栏拿取会变成循环命令方块
即使使用/give获取，获取的书架也无法在背包内移动，生存模式无法放置

## 🔍 Steps to Reproduce | 复现方法

1. 从创造物品栏拿取书架，并放入背包
2. 观察到变成循环命令方块
3. 再使用/give获取
4. 获取的书架无法在背包内移动，生存模式无法放置

## ✅ Expected Behavior | 预期行为

书架可以正常在背包内移动，放置

## 💻 OS and versions | 操作系统和核心版本

![image](https://github.com/user-attachments/assets/227019ee-ccde-46d0-97b9-e045b3118836)

* Version: ✍
* Java: OpenJDK
* Java version: 21
* Game version: Android/iOS/Win10

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

无错误日志

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by lt-name** [comment]
![img](https://github.com/user-attachments/assets/92328380-e983-4d38-9fee-e45b069fe89c)
无法复现

**Comment by FTS427** [comment]
有种可能 ta 说的是可以放书的书架？（猜测）

**Comment by explorer3039** [comment]
找到问题了，是插件的问题
