### ISSUE TITLE
Visual movement bug

### ISSUE THREAD

**Issue by Zwuiix-cmd** [MemoriesOfTime/Nukkit-MOT#318]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

Movement bug, it shakes, below 1.18 (tested in 1.12 and 1.16)。

## 🔍 Steps to Reproduce | 复现方法

Connect with 1.16。

**Comment by lt-name** [comment]
If possible, please record a video

**Comment by Zwuiix-cmd** [comment]
Basically, the player shakes, just like when we pass in big coordinates, the game doesn't show it working right, it moves while having the right position.

**Comment by Zwuiix-cmd** [comment]
I think this is due to the use of the MovePlayerPacket as a movement, the rendering isn't great, you should use the MoveActorAbsolutePacket instead.

**Comment by lt-name** [comment]
https://motci.cn/view/Nukkit/job/Nukkit-MOT-Pipeline/job/fix%252Fmovement/
Please use this branch for testing

**Comment by Zwuiix-cmd** [comment]
Yeah its good
