### ISSUE TITLE
Crash, bug memory

### ISSUE THREAD

**Issue by StefanFox-Dev** [MemoriesOfTime/Nukkit-MOT#345]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

```
Nov 23 08:00:13 env[30753]: 08:00:13 [main] [INFO] Done (7.342s)! For help, type "help"
Nov 23 08:40:23 env[30753]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "LevelDB Executor-nether #0"
Nov 23 08:40:36 env[30753]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
Nov 23 08:40:37 env[30753]: java.lang.OutOfMemoryError: Java heap space
Nov 23 08:40:37 env[30753]: 08:40:37 [BugReportGenerator] [INFO] [BugReport] Sending a bug report ...
```
Use memory: 1,4GB/16GB

## 🔍 Steps to Reproduce | 复现方法

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## 💻 OS and versions | 操作系统和核心版本

* Version: 1.20.40
* Java: OracleJDK/GraalVM/AdoptOpenJDK 
* Java version: 21 
* Game version: Android/iOS/Win10/Xbox/PS4/Switch 

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

Debug link (optional): ✍  
Spark link (optional): ✍

```error
ERROR
```

**Comment by KoshakMineDEV** [comment]
Предоставь инфы побольше, ибо просто с двумя экзепшенами без стактрейсов сложно узнать причину подобного, к тому же лично я - cannot reproduce эту ошибку.

**Comment by StefanFox-Dev** [comment]
больше информации и нет, только это

**Comment by KoshakMineDEV** [comment]
Если можешь, предоставь инфу:
- Версия и дистрибуция Java(или как там это дело называлось, крч пример - Azul Zulu JDK)
- Используется ли docker
- Ошибка была раз или происходит постоянно

**Comment by Mcayear** [comment]
nk-mot core version?

**Comment by StefanFox-Dev** [comment]
openjdk-21-jdk
version nk 1.20.40, latest
пока удалил мир nether - спокойно. 
но начались проблемы уже в world, поэтому да...
docker не используется

**Comment by KoshakMineDEV** [comment]
> Author

обновись до последних версий Nukkit-MOT и посмотри что и как будет. Мы изменили провайдер миров на Java на улучшенный. Я и до этого не смог эту проблему повторить, но после обновления тем более. 
А вообще ради интереса включи native провайдер миров, мб лучше станет

**Comment by lt-name** [comment]
Try setting `use-snappy-compression=off`
snappy may not work properly on some hardware

**Comment by StefanFox-Dev** [comment]
> > Автор
> 
> оновіть до останньої версії Nukkit-MOT і подивіться, що і як буде. Ми змінили провайдер мирів на Java на покращений. Я і до цього не зміг цю проблему повторити, але після оновлення тим більше. А взагалі ради інтересу включити рідний провайдер миров, мб краще стане

да, уже нет проблем 👍
