### ISSUE TITLE
合成的告示牌似乎无法放置

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#41]
默认特殊值告示牌可以放置
合成的其他材质告示牌不能放置
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/9ba5fb1f-22a2-44ad-8045-ad87cf9a2f08)

**Comment by glorydark** [comment]
已核实，物品方块未进行注册导致。
