### ISSUE TITLE
雪球漂浮在空中

### ISSUE THREAD

**Issue by Nissining** [MemoriesOfTime/Nukkit-MOT#47]
老问题，估计是数据包丢失问题？这种情况常发生在频繁使用雪球并在多人出现频率较高
![{34C0A44B-8985-4eb6-A91D-36862521FD3F}](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/eaef99fb-d7c0-4a1e-9ac2-f10ab9e40147)

**Comment by lt-name** [comment]
已尝试修复，请更新到最新版
