### ISSUE TITLE
Error that occurs after the latest updates

### ISSUE THREAD

**Issue by MaksKorvi** [MemoriesOfTime/Nukkit-MOT#53]
![Screenshot_20230919-224737](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92761807/246455ab-118e-4d5b-85be-2c5ba6bd9746)
![Screenshot_20230919-125043](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92761807/bf4e6bee-a118-4ae9-84bb-3257e5232f1b)
![Screenshot_20230919-125040](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92761807/8039d921-882c-4c38-a4f8-bae3d35430db)
![Screenshot_20230919-125037](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92761807/6c320db0-1a6d-4d12-8126-2289f62c7957)

**Comment by lt-name** [comment]
Please update to the latest version for testing and send the full diary if you still have problems!

**Comment by lt-name** [comment]
Since you haven't replied for a long time, I will close this issue. If you still have questions, you can reopen it.
