### ISSUE TITLE
熔炉无法燃烧矿物

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#56]
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/ccdafc09-5f51-4ab3-8cbf-3516f6e029ea)
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/70a5799c-31fa-4b6d-8176-b8e4cc36994f)

**Comment by lt-name** [comment]
粗铁熔炉配方尚未实现
