### ISSUE TITLE
未开启实验性玩法1.20玩家任然可以穿过1.5格高

### ISSUE THREAD

**Issue by BiliCloudStar** [MemoriesOfTime/Nukkit-MOT#57]
未开启实验性玩法1.20玩家任然可以穿过1.5格高
服务端:Nukkit-MOT 最新master构建
客户端:1.20.15(Only iOS)

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/110342420/3a139643-2c02-4b44-876e-cb2f8eac6ba1

![IMG_6084](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/110342420/b4958507-af93-4c6c-8872-60d75b3d1651)

**Comment by lt-name** [comment]
https://minecraft.fandom.com/zh/wiki/实验性玩法
1.20.10.23开始1.5格潜行不再属于实验性玩法

**Comment by BiliCloudStar** [comment]
移动有点问题,其他玩家视角会卡地里
