### ISSUE TITLE
Unbreakable blocks

### ISSUE THREAD

**Issue by Reider745** [MemoriesOfTime/Nukkit-MOT#73]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

Blocks do not break on the server side, blocks break on the client side, after which, when turned on, a block is placed in the place of the broken block and the broken block is returned.

## 🔍 Steps to Reproduce | 复现方法

1. Break the block
2. Try to put a block in this place.

## 📸 Screenshots / Video | 截图或视频

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/70357814/2fdbc045-b9e4-45c3-8801-13870899a5c1

In the video I break blocks in two ways: with my hands, with an explosion

## 💻 OS and versions | 操作系统和核心版本

09:36:55 [INFO ] #########################################
09:36:55 [INFO ] Nukkit-MOT
09:36:55 [INFO ] Build: master/2dd7485
09:36:55 [INFO ] Multiversion: Up to version 1.20.40
09:36:55 [INFO ] #########################################
09:36:55 [INFO ] [Nukkit-MOT] You are running the latest version.

* Java: OracleJDK
* Java version: 17
* Game version: Win10(1.20.40)

**Comment by lt-name** [comment]
https://github.com/MemoriesOfTime/Nukkit-MOT/assets/45508179/f624d463-6802-4244-ac5b-3b283fa0812c

I couldn't reproduce the problem

**Comment by Reider745** [comment]
with the help of explosive blocks the blocks break normally, but when destroyed by a player/hand the block does not break

**Comment by lt-name** [comment]
Break blocks in creative mode?
Have you tried testing without installing the plugin?

**Comment by BlusteryS** [comment]
Is the bug still reproducible on the latest versions?

**Comment by Reider745** [comment]
No
