### ISSUE TITLE
灵魂土未实现背包相关功能

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#76]
# 🐞 Bug Feedback | BUG反馈
灵魂土未实现背包功能
## 📝 Bug Description | BUG描述
灵魂土在背包内无法移动
## 🔍 Steps to Reproduce | 复现方法
在地狱群系中刷新的灵魂土，使用工具挖掘掉落的灵魂土拾取后在背包内无法移动，单击鼠标滚轮获取的灵魂土同样.

## 💻 OS and versions | 操作系统和核心版本
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/ca6e6e73-f6e9-439c-89ec-90a260883dcc)

**Comment by lt-name** [comment]
https://github.com/MemoriesOfTime/Nukkit-MOT/commit/7f0a965310a622c4bb0d9c9002a03b2846d88ddd
