### ISSUE TITLE
报错导致服务端停止服务

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#8]
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/852bd33a-2e08-4d02-b3e2-d1b0446f1480)

**Comment by CoolMagic233** [comment]
此错误出现后服务端类似于假死状态

**Comment by lt-name** [comment]
请提供下完整的日记，以便于排除问题

**Comment by CoolMagic233** [comment]
> 请提供下完整的日记，以便于排除问题

[2023-08-21-7.log](https://github.com/MemoriesOfTime/Nukkit-MOT/files/12395767/2023-08-21-7.log)

**Comment by lt-name** [comment]
已尝试修复
