### ISSUE TITLE
Cannot sleep to skip a thunderstorm during the day

### ISSUE THREAD

**Issue by rislaed** [MemoriesOfTime/Nukkit-MOT#80]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

If you try to sleep during a thunderstorm *during the day* there will be no result.

## 🔍 Steps to Reproduce | 复现方法

1. Wait for a thunderstorm
2. Make sure it was day
3. Try to go to bed to skip thunderstorm

## ✅ Expected Behavior | 预期行为

[If you have a bed, Minecraft allows you to sleep through thunderstorms, so you can sleep and when you wake up, the thunderstorm will be gone.](https://minecraft.fandom.com/wiki/Tutorials/Thunderstorm_survival#Avoiding_thunderstorms)

## 📸 Screenshots / Video | 截图或视频

![Screen-record-18bf6c52c1d 1](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92180217/7f316e19-aa22-4d87-8ac3-37fa1a25f38e)

## 💻 OS and versions | 操作系统和核心版本

* Nukkit-MOT master/8cac79a
* Version: 1.16.200.02 (protocol 422)
* Java: OracleJDK
* Java version: 17
* Platform: Android (Horizon)

**Comment by lt-name** [comment]
Fixed in [#79](https://github.com/MemoriesOfTime/Nukkit-MOT/pull/97)
