### ISSUE TITLE
When using shears, usual drop also falls out

### ISSUE THREAD

**Issue by rislaed** [MemoriesOfTime/Nukkit-MOT#82]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

If you break grass, foliage and other blocks with shears, in addition to them, usual drop will also fall, like as if you broke block with your hand.

## 🔍 Steps to Reproduce | 复现方法

1. Take shears
2. As usual, break grass or foliage

## ✅ Expected Behavior | 预期行为

There should not be an ordinary drop.

## 📸 Screenshots / Video | 截图或视频

![Screenshot_20231120-160233](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92180217/1bfea656-97b5-4ec7-931c-91a80e5d2f98)

## 💻 OS and versions | 操作系统和核心版本

* Nukkit-MOT master/8cac79a
* Version: 1.16.200.02 (protocol 422)
* Java: OracleJDK
* Java version: 17
* Platform: Android (Horizon)

**Comment by rislaed** [comment]
e0f0bf375950da21cdf00e6b766b698d912352c3

**Comment by glorydark** [comment]
It seems that lt-name has tried to fix it in a previous commit. I will test it after downloading the latest build.

**Comment by glorydark** [comment]
it proved to be true in the latest build
