### ISSUE TITLE
Droppers and dispensers drops from wrong side

### ISSUE THREAD

**Issue by rislaed** [MemoriesOfTime/Nukkit-MOT#83]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

Activation of droppers leads to dropping of the item from wrong side (+1?), although the meta on server and the client are the same. Only exception for the last meta (5).

## 🔍 Steps to Reproduce | 复现方法

1. Place a dropper or dispenser
2. Put items in it, no matter how many and where
3. Activate it with a redstone signal in any way

## ✅ Expected Behavior | 预期行为

Drop from the right side, obviously.

## 📸 Screenshots / Video | 截图或视频

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92180217/97e6e0dc-9d05-453f-bd67-14ceba4df8f0

## 💻 OS and versions | 操作系统和核心版本

* Nukkit-MOT master/8cac79a
* Version: 1.16.200.02 (protocol 422)
* Java: OracleJDK
* Java version: 17
* Platform: Android (Horizon)

**Comment by BlusteryS** [comment]
fixed in https://github.com/MemoriesOfTime/Nukkit-MOT/pull/90, wait for release
