### ISSUE TITLE
Extreme spruce grows from a random sapling

### ISSUE THREAD

**Issue by rislaed** [MemoriesOfTime/Nukkit-MOT#87]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

To grow an extreme spruce and a jungle tree, 4 saplings are needed, but the tree grows from a random one instead. Perhaps it somehow depends on the bone meal.

## 🔍 Steps to Reproduce | 复现方法

1. Place 4 saplings of spruce or jungle
2. Use bone meal to accelerate growth

## ✅ Expected Behavior | 预期行为

All 4 saplings should be replaced with a tree.

## 📸 Screenshots / Video | 截图或视频

![Screenshot_20231118-210724](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92180217/4821619b-7583-4326-aa6a-a73eddcea872)

## 💻 OS and versions | 操作系统和核心版本

* Nukkit-MOT master/8cac79a
* Version: 1.16.200.02 (protocol 422)
* Java: OracleJDK
* Java version: 17
* Platform: Android (Horizon)

**Comment by glorydark** [comment]
Quite weird. Waiting for the fix.
