### ISSUE TITLE
漏斗矿车似乎无法正常工作

### ISSUE THREAD

**Issue by CoolMagic233** [MemoriesOfTime/Nukkit-MOT#9]
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/e4ef5e78-0d73-4341-addd-0e882444b36c)
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/ebf45733-5b97-49f4-8dd8-7df66756aced)
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/3cf0d3ec-411c-4511-a62f-1ee21018cea1)
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/91107923/052d2d8c-e2f2-4556-ac7d-aea8731ad117)
如图?

**Comment by glorydark** [comment]
经测试，漏斗矿车、运输矿车这样搭建均无法将物品穿到下方漏斗。
