### ISSUE TITLE
A falling block replaces another falling block

### ISSUE THREAD

**Issue by rislaed** [MemoriesOfTime/Nukkit-MOT#94]
# 🐞 Bug Feedback | BUG反馈

## 📝 Bug Description | BUG描述

Blocks falling on each other can replace blocks that have fallen below, losing the drop.

## 🔍 Steps to Reproduce | 复现方法

1. I placed 8 sand up under player
2. Destroy any block below, and then more, more, more
3. Got 4 sand, where is my sand

## ✅ Expected Behavior | 预期行为

Falling blocks should fall on each other, and not be replaced by falling on another block.

## 📸 Screenshots / Video | 截图或视频

https://github.com/MemoriesOfTime/Nukkit-MOT/assets/92180217/01b771df-d9fd-4bda-8ec4-c067e04d614a

## 💻 OS and versions | 操作系统和核心版本

* Nukkit-MOT master/8cac79a
* Version: 1.16.200.02 (protocol 422)
* Java: OracleJDK
* Java version: 17
* Platform: Android (Horizon)

**Comment by lt-name** [comment]
Added a temporary fix, which should temporarily alleviate this issue
