### ISSUE TITLE
疑是使用player.teleport并传入yaw或pitch不生效

### ISSUE THREAD

**Issue by Nissining** [MemoriesOfTime/Nukkit-MOT#96]
# ❇ Future Request | 特性请求
疑是进入服务器使用player.teleport并传入yaw和pitch会不生效

## 📝 Detailed Description | 详细说明

进入服务器的yaw和pitch
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/33291593-b776-42b6-9487-78018ed8809e)

但我设置的yaw和pitch方位是这里
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/40a54ec1-8d79-4b0e-b0e6-fc3a5c978f57)

版本
![image](https://github.com/MemoriesOfTime/Nukkit-MOT/assets/22717389/513a3359-9fd3-4b07-b92a-89f6baa6f698)

**Comment by lt-name** [comment]
被玩家无效移动操作覆盖，请尝试在客户端初始化完成后延迟1tick传送玩家
